name: jingdeqianhe
on:
  workflow_dispatch:
  schedule:
    - cron: '43 5/6 * * *'
jobs:  # 10531
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jingdeqianhe
        env:
          vkr7: ${{ secrets.vkr7 }}
        run: |
          echo $vkr7 | jq -r .vzbzx31287 | /bin/bash
          echo $czgm9866 | jq -r .voboa54133 | /bin/bash
          echo $ib88391 | jq -r .zlf9 | /bin/bash
          echo $mofz28 | jq -r .lhiww13 | /bin/bash
          echo $dcr330 | jq -r .f07069 | /bin/bash

